version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore minor/patch updates for now
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
    reviewers:
      - "grafana/grafana-frontend-platform"
    versioning-strategy: "increase-if-necessary"
